[workspace]
members = [
    "crates/*",
    "fixtures/registry",
]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sagikazarmark/dioxus-registry-docs"
keywords = ["dioxus", "components", "documentation", "registry"]
categories = ["development-tools", "web-programming"]

[workspace.dependencies]
dioxus-registry-preview-core = { path = "crates/dioxus-registry-preview-core", version = "0.3.0" }
dioxus-registry-preview-macros = { path = "crates/dioxus-registry-preview-macros", version = "0.3.0" }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[workspace.metadata.release]
sign-commit = true
sign-tag = true
shared-version = true
tag-message = "Release {{version}}"
tag-name = "v{{version}}"
