[package]
name = "dioxus-registry-preview-core"
version.workspace = true
description = "Core discovery, validation, and rendering for Dioxus component Registry Previews"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
proc-macro2 = "1.0.101"
pulldown-cmark = "0.13.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
syn = { version = "2.0.98", features = ["extra-traits", "full"] }
url = "2.4.0"

[lints]
workspace = true
